# Generated by Django 5.0.7 on 2024-07-27 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=20)),
                ('line_type', models.CharField(max_length=20)),
                ('vendor_name', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('description', models.TextField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(max_length=20)),
            ],
        ),
    ]
