# Generated by Django 5.0.7 on 2024-07-30 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0003_modelwithfilefield_modelwithimagefield_delete_plant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelwithfilefield',
            name='name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='modelwithimagefield',
            name='name',
            field=models.CharField(max_length=500),
        ),
    ]
