# Generated by Django 5.0.7 on 2024-08-02 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0005_rename_name_modelwithfilefield_file_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tran_type', models.CharField(choices=[('PMT', 'Payment'), ('INV', 'Invoice'), ('CRN', 'Credit Note'), ('REF', 'Refund')], max_length=20)),
                ('doc_id', models.CharField(blank=True, max_length=30, null=True)),
                ('doc_date', models.DateField()),
                ('vendor_name', models.TextField(max_length=60)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('file', models.FileField(upload_to='files/')),
            ],
        ),
    ]
