# Generated by Django 5.0.7 on 2024-08-02 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0006_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='vendor_id',
            field=models.CharField(default='xxx001', max_length=20),
            preserve_default=False,
        ),
    ]
